
workflows:
  ios-workflow:
    name: iOS Workflow
    # instance_type: mac_pro
    max_build_duration: 120
    environment:
      groups:
          - firebase
          - ios
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace" 
        BUNDLE_ID: com.example.flutterFirebaseServices # <-- Put your bundle id here dhfkdsf
      flutter: stable
      xcode: 13.1
      cocoapods: default
    scripts:
      - name: Cmod
        script: |
           chmod 0600 ~/.netrc 
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_ADHOC --create
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --project=ios/Runner.xcodeproj
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
          --build-name=1.0.0 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1)) \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log 
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
        firebase:
          firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
          ios:
            app_id: 1:794145853480:ios:29e26c060cb9c6d127251d
            groups: # Add one or more groups that you wish to distribute your iOS application to, you can create groups in the Firebase console
              - nihal
